Gemfile, Gemfile.lock, app/controllers/Users/passwords_controller.rb, app/controllers/Users/registrations_controller.rb, app/controllers/Users/sessions_controller.rb, app/models/user.rb, app/views/users/passwords/new.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230803150816_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
執行了以下指令，並整理了 gemfile
還未開 model
-------
bundle add devise
rails generate devise:install
並
edit: config/environments/development.rb
=> feat: bundle add devise & g devise:install

app/mailers/user_mailer.rb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/user_mailer/reset_password_instructions.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, config/locales/en.yml, config/locales/tw.yml
加入 footer 畫面切版，先做一個假的 footer 樣式
Logo 未定，之後可以換，連結未設定
=> style: 加入 footer 畫面切版

app/controllers/profiles_controller.rb, app/models/profile.rb, app/views/profiles/_form.html.erb, app/views/profiles/index.html.erb, app/views/profiles/show.html.erb
1. profiles/new 頁面
- 新增 上傳影片功能
- 檔案格式只能選擇 MP4
2. profiles/:id 頁面
- 影片顯示在音樂底下
- 可以隨時播放和暫停
- 可以全螢幕
- 調整播放速度和音量
- 沒有上傳影片則顯示
3. 有螢幕錄影，可以觀看整個過程
https://www.youtube.com/watch?v=dEcHoYgBTH0
=> Feat : Profile 上傳影片 / show 頁面會有影片

Gemfile, Gemfile.lock, app/controllers/bands_controller.rb, app/models/band.rb, app/models/style.rb, app/views/bands/_band.html.erb, app/views/bands/_band_cards.html.erb, app/views/bands/index.html.erb
搜尋框  + 曲風複選框 可以複合使用
目前搜尋框只有開放團名跟曲風,  就是在框裡面打曲風也可以搜尋到想要的, 
只按 checkbox 也可以進行搜尋 
https://github.com/astrocamp/14th-JoBand/assets/132435587/79a28b5a-47bc-490f-a77c-1272ebf47cfc
樣式
=> Feat: 樂團搜尋 

app/controllers/bands_controller.rb, app/models/band.rb, app/views/bands/_band.html.erb, app/views/bands/_form.html.erb, app/views/bands/_style.html.erb, app/views/bands/show.html.erb
1. 有螢幕錄影，但檔案太大，所以放到 Youtube（背景音樂是我螢幕錄影忘記關掉的！可以先靜音再看XD）
https://youtu.be/lpH2FdBYl-Y
2. bands 的上傳音樂和影片跟做 profiles 基本上都一樣，另外排版有做一點調整
- bands/new 頁面
- bands/:id 頁面
- bands 頁面
=> feat : bands 上傳音樂和影片 / 修改一些 bands 的 CSS，讓畫面更清楚

app/helpers/application_helper.rb, app/helpers/profiles_helper.rb, app/views/profiles/index.html.erb, app/views/recruits/_form.html.erb, app/views/recruits/edit.html.erb, app/views/recruits/index.html.erb, app/views/recruits/new.html.erb, app/views/recruits/show.html.erb
招募頁面的切版
以下是螢幕錄影 ：
https://youtu.be/mguuwXjss_k
=> Style : 召募頁面的切版 + 更新 instruments_all

app/models/user.rb, app/views/users/shared/_links.html.erb
=>  Style: add oauth btn CSS 新增第三方登入外觀

app/controllers/bands_controller.rb, app/models/band_member.rb, app/views/bands/_form.html.erb, app/views/bands/_member.html.erb, db/migrate/20230824070202_change_band_members_columns.rb, db/schema.rb
把 `band_role` , 改成 `identity`, 
`identity` 分成 ` leader , manager , member `, 創立樂團的預設為 `leader`
增加 ` role ` 欄位 , 紀錄 user 在 band 裡的職位
`樂團 new` 會多一個 , role 的下拉選單 , 創立樂團後 `role` 會自動寫入, `Band_member`
https://github.com/astrocamp/14th-JoBand/assets/132435587/bf5bc767-7f6f-47f2-b9d0-5b5dd8249b51
<h1>樣式</h1>
=> Feat: Band 增加 職位 的欄位

app/models/profile.rb, app/views/profiles/show.html.erb, app/views/shared/_instrument.html.erb
修改 instrument render 錯誤，之前會顯示不出 listener
修改完後可以正常顯示
=> fix: instrument render typo

app/controllers/Users/confirmations_controller.rb, app/controllers/Users/registrations_controller.rb, app/controllers/recruits_controller.rb, app/views/bands/show.html.erb, app/views/recruits/_form.html.erb, app/views/recruits/index.html.erb, app/views/recruits/show.html.erb, config/routes.rb, db/migrate/20230825100739_change_recruits_column.rb, db/schema.rb
=> feat:增加Band Show頁面可連結至Recruit功能

app/controllers/profiles_controller.rb, db/migrate/20230829043256_change_profile_tel_type_to_string.rb, db/seeds.rb
- 修改了 profile update 後會跑到 index 的錯誤
目前修改後會載入到 profile show 頁面
- 另外也修改了 phone 欄位為字串屬性
- 假資料從火星回到LA了
=> fix: profile update and change the type of phone to string

app/assets/stylesheets/application.css, app/controllers/profiles_controller.rb, app/javascript/application.js, app/javascript/controllers/flash_controller.js, app/views/layouts/application.html.erb, app/views/layouts/home.html.erb, app/views/shared/_flash.html.erb, config/importmap.rb
把 flash notice / alert 改為 sweetalert2 的樣式
如下圖 
當有成功的 notice 出來時候
當有失敗的 alert 出來的時候
之後大家只要在 controller 那邊有用到 flash 他就會根據你寫的是 alert 或 notice 顯示 打勾 或是驚嘆號
=> Feat: modify the flash with sweetalert2

app/javascript/controllers/showband_controller.js, app/views/shared/_myband.html.erb, app/views/shared/_navbar.html.erb
新增 navbar 點選我的樂團後會動態新增目前有的樂團並附上連結
目前功能完善（ 點了會顯示再點一次就收回去 ）也能連到該樂團的 show
CSS 部分之後會再開票去修正 ( 跟 S2 RWD )
=> feat: add function to show the user's band on navbar

app/controllers/application_controller.rb, app/controllers/band_members_controller.rb, app/controllers/bands_controller.rb, app/controllers/profiles_controller.rb, app/helpers/band_members_helper.rb, app/helpers/bands_helper.rb, app/views/band_members/_band_member.html.erb, app/views/band_members/edit.html.erb, app/views/bands/_form.html.erb, app/views/bands/_member.html.erb, app/views/bands/edit.html.erb, app/views/bands/index.html.erb, app/views/bands/show.html.erb, app/views/profiles/index.html.erb, app/views/profiles/show.html.erb, app/views/recruits/show.html.erb, config/routes.rb, db/migrate/20230825100739_change_recruits_column.rb, db/schema.rb
<h1>Main</h1>
預設只有團長可以看見編輯紐 , 
可以編輯樂團成員在樂團中擔任的職位 `role`
或者是身分 `identity`  
但是目前有一個小bug 就是, 團長把自己職位改掉的話 , 畫面就會爆炸
<h2>Other</h2>
順便改了一下 partial render 的位置 , 
和一些 code reveiw 的小改動, 
修正 編輯樂團資訊時的錯誤 (會帶入role)
<h2>Demo</h2>
https://github.com/astrocamp/14th-JoBand/assets/132435587/70e42bf8-3793-4d25-ad02-2447d7ccf11a
=> Feat: 編輯樂團成員功能

app/views/bands/_band.html.erb, app/views/bands/_form.html.erb
=> fix: fix typo

Gemfile, app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/users/shared/_links.html.erb, config/initializers/devise.rb, db/migrate/20230829083949_remove_oauth_from_users.rb, db/migrate/20230829084108_add_oauth_to_users.rb
1. Facebook 登入暫時先拿掉
2. google 登入按鈕更新如下
3. 重構第三方登入程式碼
簡化原本的程式碼修正一些問題。
=> Refactor: 重構程式碼，不影響功能，只是改進程式碼結構＆可讀性。

app/views/band_members/_band_member.html.erb, app/views/bands/_band.html.erb, app/views/bands/show.html.erb, app/views/recruits/show.html.erb, app/views/users/shared/_links.html.erb, db/schema.rb, db/seeds.rb
調整了昨天會遇到的一些錯誤
目前沒登入沒profile點招募中會轉到註冊及登入頁面
成員排排站
如果沒招募又是自己的樂團會看到修改樂團
如果不是樂團所有者而當樂團又有招募會看到招募中
=> fix: hotfix for demo

.env.sample, Gemfile, Gemfile.lock, config/environments/development.rb, config/storage.yml
1. 這邊以 profile 的大頭貼來進行測試～
2. 更新完檔案上傳的資料後，成功存入 Amazon s3 的雲端服務，重整 Amazon s3 網頁也可以看到紀錄！
ps 之後要 demo 檔案上傳的部分，都要抓檔案小的資料，不然會跑很久
https://github.com/astrocamp/14th-JoBand/assets/38303979/d1731430-2c49-4042-9f3b-9eda16b8a425
=> Feat : 將檔案利用 Amazon s3 服務上傳成功

app/views/profiles/index.html.erb, app/views/shared/_instrument.html.erb
profile index 的搜尋新增以 icon 來搜尋
點了 icon 後會直接顯示搜尋結果
https://github.com/astrocamp/14th-JoBand/assets/135109935/bcc88bbc-c571-4db8-8a8a-4ba415d36f1c
=> Profile 樂器搜尋 filter

app/controllers/resume_lists_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/bands/show.html.erb, app/views/resume_lists/show.html.erb, config/routes.rb
新增拒絕申請的按鈕 在加入或拒絕都增加一層 確認
https://github.com/astrocamp/14th-JoBand/assets/132435587/e3e3cf14-dfc5-4f90-a970-795bbc04ab1f
=> Feat: 新增拒絕申請按鈕

app/controllers/resume_lists_controller.rb, app/models/recruit.rb, app/views/resume_lists/show.html.erb
1.
edit 的時候 , 路徑跟 new 不一樣, 沒有嵌套到上層的 `招募`,
所以抓不到 `招募` 需要的 `role` , 故無法編輯 ,
另外寫方法, 用`申請表`去抓`招募`需要的`role` , 
把 new 跟 edit 需要的, 用判斷式分開, 再丟進 partial render
2. 
刪除關聯,加 `dependent: :destroy `, 在招募刪除的時候 , 把申請也一併刪除
https://github.com/astrocamp/14th-JoBand/assets/132435587/f4be72e7-de81-4cd0-851a-61ae47aebb33
=> Feat: 樂團申請 的 編輯功能

app/views/resume_lists/_form.html.erb
=> fix: hot fix resume list

app/assets/stylesheets/application.css, app/assets/stylesheets/application.tailwind.css, app/views/pages/index.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, public/icon_img/light.svg
- light mode nav / footer 調整
- navbar 下拉選單 hover 調整
- footer 不必要的順手先刪除了
=> 更加強調 light mode

app/controllers/profiles_controller.rb, app/models/band.rb, app/policies/application_policy.rb, app/policies/profile_policy.rb
HOT FIX
沒有登入的狀態，profile#show，band#show 會壞掉！
感恩 @zhanjian0217  @andy840818
=> Hot fix : 為了上午的 Demo, 先從大ＰＲ中，獨立出來

app/controllers/api/v1/posts_controller.rb, app/controllers/posts_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/like_controller.js, app/models/like_log.rb, app/models/post.rb, app/models/user.rb, app/views/posts/index.html.erb, config/routes.rb, db/migrate/20230906214424_create_like_logs.rb
新增貼文按讚功能
https://github.com/astrocamp/14th-JoBand/assets/140575755/3ae27028-1dd0-4bd5-886f-d1051af4efa8
=> feat: 新增貼文按讚功能

app/controllers/activities_controller.rb, app/models/activity.rb, app/views/activities/activity_index.html.erb, app/views/activities/index.html.erb
增加活動搜尋功能
可搜尋 標題 內文 及樂團名稱
搜尋標題
搜尋樂團
=> feat:增加活動搜尋功能

Gemfile.lock, app/controllers/comments_controller.rb, app/controllers/recruits_controller.rb, app/controllers/resume_lists_controller.rb, app/models/band.rb, app/policies/recruit_policy.rb, app/policies/resume_list_policy.rb, app/views/recruits/show.html.erb, app/views/resume_lists/show.html.erb, public/403.html
用影片演示有點複雜, 直接以文字描述
<h1> 招募 recruit </h1>
招募比較單純，只設定團長的角色
- show 
所有人都能看到
- new , create , edit , update , destroy 
只有此團 團長可以執行
放了一個 apply? , 只是為了判斷誰可以看到申請的按鈕
<h1> 申請 resume_list </h1>
- show 
1. 申請者本人 2.此團團長 3.管理員
- create , new 
1. 有 profile 的 user 2. 非本團的團員 3. **尚未**對此招募提出過申請的人
- edit , update 
1. 申請者本人
- approve , reject 
1. 團長
=> Feat: 招募和申請的權限 

README.md
=> docs: README 更新

app/assets/stylesheets/application.css, app/assets/stylesheets/direct_uploads.css, app/javascript/application.js, app/javascript/direct_uploads.js, app/models/activity.rb, app/views/activities/_form.html.erb, app/views/bands/_form.html.erb, app/views/bands/show.html.erb, app/views/profiles/_form.html.erb, app/views/profiles/show.html.erb, config/environments/development.rb
- 每個頁面的播放器，雖然還是預設的，但加了漸層顏色，有一點不同的感覺
- 有需要的話，顏色可以再調
- 每個新增與更新需要上傳的頁面，都有做預設動畫，按下按鈕送出，才會開始跑
https://github.com/astrocamp/14th-JoBand/assets/38303979/9087060e-098a-4f05-8c76-843c9f30096c
- 下一個 PR 我會做 "時間驗證" ，這邊空格會一起修改，請大家先忽略
=> Feat : S3 direct uploads + 音樂播放器增添色彩

app/controllers/activities_controller.rb, app/controllers/posts_controller.rb, app/controllers/profiles_controller.rb, app/policies/activity_policy.rb, app/policies/band_policy.rb, app/policies/post_policy.rb, app/policies/profile_policy.rb, app/views/activities/show.html.erb, app/views/bands/show.html.erb, app/views/posts/_new.html.erb, app/views/posts/index.html.erb
<h1> 修正 profile new </h1>
已經有profile 的人 , 不能再創 profile
( 雖然原本也創不起來,但就導到403頁面 )
<h1> 活動 activity </h1>
- new , create , destroy
1. 團長
- edit update
1. 團長 2. 管理員
<h1> 貼文 post </h1>
- new , create 
1. 有 profile 的 user
- edit ,  update , destroy
1. 貼文擁有者
=> Feat: 活動 & 貼文 權限

app/controllers/activities_controller.rb, app/controllers/api/v1/posts_controller.rb, app/controllers/comments_controller.rb, app/controllers/profiles_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/devise_helper.rb, app/models/activity.rb, app/models/like_log.rb, app/models/post.rb, app/models/user.rb, app/policies/activity_policy.rb, app/policies/post_policy.rb, app/policies/profile_policy.rb, app/views/layouts/application.html.erb, app/views/profiles/welcome.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb
修復 login 部分字顏色不會搭配亮暗色調調整。
修正 會出現 sweetalert2 404錯誤。
=> style: 修復 login 部分字顏色不會搭配亮暗色調調整。sweetalert2 404錯誤 移除

app/controllers/api/v1/posts_controller.rb, app/controllers/posts_controller.rb, app/javascript/controllers/like_controller.js, app/views/posts/index.html.erb
like 修好了
https://github.com/astrocamp/14th-JoBand/assets/128116961/572ca7a7-9fc5-4431-8e6b-3427b1bf569e
=> fix: like button fixed

app/controllers/application_controller.rb
如影片：
https://github.com/astrocamp/14th-JoBand/assets/128116961/45db79bd-c9ca-46dd-a308-251d805390e5
=> feat: i18n 固定住，改成其他地區會自動跳回 tw

app/views/layouts/application.html.erb
=> hotfix: remove container from main

app/views/profiles/index.html.erb
=> fix: profile index search CSS

app/views/activities/activity_index.html.erb, app/views/activities/show.html.erb, app/views/profiles/_form.html.erb, app/views/profiles/_profile.html.erb, app/views/profiles/show.html.erb, app/views/recruits/_form.html.erb
=> fix : profile finish fix + 其他發現的錯誤一併修改

app/views/activities/_form.html.erb, app/views/activities/edit.html.erb, app/views/activities/index.html.erb, app/views/activities/new.html.erb, app/views/bands/edit.html.erb, app/views/bands/new.html.erb, app/views/bands/show.html.erb, app/views/profiles/_form.html.erb, app/views/profiles/letsjam.html.erb, config/locales/tw.yml
- 每個 **show** 頁面，底下都是： **' 創建' ...** / **'修改' ...**
- 每個 **new** 頁面
1 上面都是： **'創建您的' ...** 
2 底下都是： **'建立' ...**
- 每個 **edit** 頁面
1 上面都是： **'修改您的' ...** 
2 底下都是： **'更新' ...**
=> docs : some page descriptions 更新一些描述

app/assets/stylesheets/application.css, app/assets/stylesheets/application.tailwind.css, app/views/activities/_activity.html.erb, app/views/activities/activity_index.html.erb, app/views/activities/index.html.erb, app/views/bands/_band.html.erb, app/views/bands/_style.html.erb, app/views/bands/index.html.erb, app/views/bands/show.html.erb, app/views/profiles/_form.html.erb, app/views/profiles/_profile.html.erb, app/views/profiles/index.html.erb, app/views/profiles/show.html.erb, app/views/shared/_instrument.html.erb
- profile / band / activities 的 index CSS RWD
- profile / band card 統一格式 RWD
- profile / band show 統一格式 RWD
- profile new & edit 統一格式 RWD
一些按鈕統一
未做待做：
activity show / band new edit
https://github.com/astrocamp/14th-JoBand/assets/135109935/cb85528b-8b7b-4981-a10a-f11e7795e66a
=> Css RWD update

app/assets/stylesheets/application.css, app/views/bands/_form.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_notifications.html.erb, config/locales/tw.yml
- 調整 band / new edit 
- 調整 小鈴鐺位置與大小
https://github.com/astrocamp/14th-JoBand/assets/135109935/9cfa86f1-61f2-43d8-917a-059967b39311
=> Css adjust 2 CSS & RWD 調整 band new & edit & notification 位置 

app/assets/stylesheets/application.css, app/javascript/controllers/flash_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/submited_controller.js, app/models/activity.rb, app/models/band.rb, app/models/profile.rb, app/views/activities/_form.html.erb, app/views/bands/_form.html.erb, app/views/profiles/_form.html.erb, config/locales/en.yml, config/locales/tw.yml
在Profile, Band, Activity
檔案開始上傳後，按鈕會呈現 JoBand 灰，並且 disable
並限制檔案大小，目前限制：
- 頭像 3Mb
- Banner 5Mb
- 音樂 10Mb
- 影片 20Mb
超過大小上傳後會擋，並且跳錯誤通知
https://youtu.be/GHob4S45asM
=> feat: 檔案上傳時, submit 應該要disable, 並限制檔案大小

app/helpers/posts_helper.rb
=> docs: post avatar set variant to resize

app/controllers/comments_controller.rb
=> fix:留言的控制器修正

app/controllers/bands_controller.rb, app/controllers/resume_lists_controller.rb, app/helpers/recruits_helper.rb, app/models/band.rb, app/models/notification.rb, app/models/profile.rb, app/models/resume_list.rb, app/models/user.rb, app/notifications/resume_list_notification.rb, app/policies/recruit_policy.rb, app/views/recruits/show.html.erb, app/views/resume_lists/show.html.erb, app/views/shared/_notification.html.erb, app/views/shared/_notifications.html.erb, config/locales/en.yml, config/locales/tw.yml
1. 點擊通知後, 消除通知
https://github.com/astrocamp/14th-JoBand/assets/132435587/d35493ad-79ae-4d5a-8ed7-22eda4f17c0f
2. 申請的顯示判斷
3. 小鈴鐺改回顯示數字
=> Feat: 點擊通知時, 消除通知

app/views/pages/index.html.erb
幫video增加一個屬性 "playsinline" 讓手機版能自動播放
=> docs: set index video auto play on mobile

db/seeds.rb
=> fix: update seed.rb

app/controllers/bands_controller.rb, app/models/band_member.rb, app/notifications/band_member_notification.rb, app/views/shared/_notifications.html.erb, config/locales/tw.yml
現在user新加入樂團，團長approve後會收到“歡迎加入樂團” 點及通知後 會到樂團的show頁面，同時會移除通知
=> Feat: 新增加入樂團通知

app/controllers/posts_controller.rb, app/views/posts/index.html.erb
只要有活動，每次重新整理就會隨機抓一張，並且可以連結到活動show頁面
=> style:  討論區 右邊活動Banner

app/views/users/registrations/new.html.erb
=> fix:註冊頁面RWD

app/controllers/bands_controller.rb, app/controllers/channels_controller.rb, app/controllers/posts_controller.rb, app/models/band.rb, app/models/channel.rb, app/models/post.rb, app/models/user.rb, app/views/channels/_controls.html.erb, app/views/channels/_new.html.erb, app/views/channels/_posts.html.erb, app/views/channels/show.html.erb, app/views/posts/index.html.erb, config/routes.rb, db/migrate/20230914094813_create_channels.rb, db/migrate/20230914100651_add_relation_to_channel.rb, db/migrate/20230914140512_remove_column_in_channel.rb, db/schema.rb, db/seeds.rb
=> feat: 討論區左邊欄，樂團聊天室完成！

app/controllers/bands_controller.rb, app/controllers/comments_controller.rb
=> fix: notice & comment

app/views/posts/index.html.erb, db/schema.rb
=> fix:修正討論區活動顯示時間 並增加日期

app/controllers/comments_controller.rb, app/views/channels/_controls.html.erb, app/views/channels/_posts.html.erb, app/views/comments/_comment_channel.html.erb, config/routes.rb
由於目前turbo的關係,留言刪除會遇到turbo misssing的問題
因此暫時先拔除刪除
=> feat: 新增討論區樂團頻道留言功能

app/controllers/activities_controller.rb, app/controllers/bands_controller.rb, app/controllers/comments_controller.rb, app/controllers/posts_controller.rb, app/controllers/profiles_controller.rb, app/controllers/recruits_controller.rb, app/controllers/resume_lists_controller.rb, app/views/activities/_form.html.erb, app/views/activities/show.html.erb, app/views/band_members/edit.html.erb, app/views/bands/new.html.erb, app/views/bands/show.html.erb, app/views/channels/_controls.html.erb, app/views/channels/_new.html.erb, app/views/channels/_posts.html.erb, app/views/channels/show.html.erb, app/views/comments/_comment_activity.html.erb, app/views/comments/_comment_post.html.erb, app/views/comments/_comment_resume.html.erb, app/views/posts/_controls.html.erb, app/views/posts/_new.html.erb, app/views/posts/_posts.html.erb, app/views/posts/index.html.erb, app/views/profiles/show.html.erb, app/views/recruits/index.html.erb, app/views/recruits/show.html.erb, app/views/resume_lists/_form.html.erb, app/views/resume_lists/show.html.erb, config/locales/en.yml, config/locales/tw.yml
=> feat: add more i18n

app/views/shared/_footer.html.erb, config/environments/development.rb, db/seeds.rb
開發模式 storage 換成 local
seed 加小註解
=> docs: 開發模式 storage 換成 local，seed 加小註解

app/views/activities/show.html.erb
=> fix: activity

app/views/activities/_form.html.erb, app/views/activities/edit.html.erb, app/views/activities/new.html.erb
修改 activity new / edit RWD CSS
https://github.com/astrocamp/14th-JoBand/assets/135109935/b3ed56c5-7ad1-44ed-beac-818d36ee0f93
=> style: activities new edit CSS/RWD

app/assets/stylesheets/application.css, app/views/bands/show.html.erb, app/views/profiles/show.html.erb, config/storage.yml
電腦和手機版的播放器樣式，改為原樣
改 Amazon 的儲存庫名字
=> chore : 更新 AWS + 播放器樣式

app/views/shared/_navbar.html.erb
下拉選單改為點擊外側可以收合
https://github.com/astrocamp/14th-JoBand/assets/135109935/969dd894-5865-4589-9819-2b25587b0d15
=> docs: close dropdown by click outside

app/views/posts/_posts.html.erb, app/views/posts/index.html.erb
- 修改 post  打太長會爆版問題
- 修改 當有按讚又有留言時候數字會跑版問題 ( 這邊跟靂佑的 PR 為主，影片這段請忽略 )
https://github.com/astrocamp/14th-JoBand/assets/135109935/324e0cb9-5434-48a6-a6b2-80d69af3230f
=> docs: fix post with long text

app/views/comments/_comment_post.html.erb, app/views/posts/_new.html.erb, app/views/posts/index.html.erb
=> style:修正post頁面留言太長會爆版以及按讚跑版問題

app/views/shared/_footer.html.erb, config/locales/en.yml
1. 修正 band form 的 en 版 
2. 本人私心想改 footer  不然有點偏空
=> Style: footer 樣式
